modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/gallery/issues"
license = "https://github.com/team-abnormals/gallery/blob/main/LICENSE.txt"

[[mods]]
    modId = "gallery"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "minecraft:painting"
    configBackground = "minecraft:textures/block/wool.png"
    authors = "Team Abnormals"
    credits = "bageldotjpg, snake block, Musicano"
    displayURL = "https://www.teamabnormals.com/mods/gallery"
    displayName = "Gallery"
    description = '''
    Adds icons for all painting variants and some more painting tweaks!
    '''

[[dependencies.gallery]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.20.2)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.gallery]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.1.3,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.gallery]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[7.1.0,)"
    ordering = "AFTER"
    side = "BOTH"