modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/team-abnormals/gallery/issues"
license = "https://github.com/team-abnormals/gallery/blob/main/LICENSE.txt"

[[mixins]]
    config = "gallery.mixins.json"

[[mods]]
    modId = "gallery"
    version = "${mod_version}"
    logoFile = "logo.png"
    itemIcon = "minecraft:painting"
    configBackground = "minecraft:textures/block/wool.png"
    authors = "Team Abnormals"
    credits = "bageldotjpg, snake block, Musicano"
    displayURL = "https://www.teamabnormals.com/mods/gallery"
    displayName = "Gallery"
    description = '''
    Adds icons for all painting variants and some more painting tweaks!
    '''

[[dependencies.gallery]]
    modId = "minecraft"
    type = "required"
    versionRange = "[${mc_version}]"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.gallery]]
    modId = "neoforge"
    type = "required"
    versionRange = "[${neoforge},)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.gallery]]
    modId = "blueprint"
    type = "required"
    versionRange = "[${blueprint},)"
    ordering = "AFTER"
    side = "BOTH"